apps/cliente/urls.py
from django.conf.urls import url, include
from apps.cliente.views import index,pagos, perfilCliente, carritoCliente, editarInformacion_view,listaDeseos,editarPedido,eliminarPedido,crearPedido, mostrarPedidos,eliminarFavorito 


urlpatterns =[ 
    url(r'^$',index, name='index'),
    url(r'^perfil$',perfilCliente,name='perfil'),
    url(r'^carrito$',carritoCliente,name='carrito'),
    url(r'^pedidos$',mostrarPedidos, name='pedidos'),
    url(r'^crearPedido$',crearPedido, name='crearPedido'),
    url(r'^editarInf/(?P<id_user>.*)$',editarInformacion_view, name='editarInf'),
    url(r'^editarPed/(?P<idp>.*)$',editarPedido, name='editarPed'),
    url(r'^deseos$',listaDeseos, name='deseos'),
    url(r'^pagos$',pagos, name='pagos'),
    url(r'^deleteP/(?P<idp>.*)$',eliminarPedido, name='deleteP'),
    url(r'^deleteFav/(?P<idf>.*)$',eliminarFavorito, name='deleteFav'), 
]

iSeller/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^cliente/', include('apps.cliente.urls')),
    url(r'^registro/', include('apps.registro.urls')),
    url(r'^proveedor/', include('apps.proveedor.urls')),
    url(r'^intermediario/', include('apps.intermediario.urls')),
    url(r'^tienda/', include('apps.tienda.urls')),
    url(r'^',include('apps.dashboard.urls')),
]

apps/carrito/models.py
from django.db import models

# Create your models here.

apps/cliente/models.py
from django.db import models

from apps.registro.models import Persona
from apps.proveedor.models import Producto
# Create your models here.

class Cliente(models.Model):
    idCliente = models.AutoField(primary_key=True)
    persona = models.OneToOneField(Persona,null=False,blank=False, on_delete=models.CASCADE)
    ##Falta id carrito de compras 

#tabla de lista de pedidos de cada cliente
class Pedidos(models.Model):
	idPedido = models.AutoField(primary_key=True)
	idCliente = models.ForeignKey(Cliente,on_delete=models.CASCADE)
	nombre = models.CharField(blank=True, max_length=100)
	descripcion = models.TextField(null=False, max_length=500)
	categoria = models.CharField(max_length=10)
	estado = models.BooleanField(default=True)
	solicitudes = models.IntegerField(default=0)
	fecha_pedido = models.DateField()

#tabla de lista de deseos
class Lista_deseos(models.Model):
	idProducto = models.ForeignKey(Producto,null=False,blank=False,on_delete=models.CASCADE)
	idCliente = models.ForeignKey(Cliente,null=False,blank=False,on_delete=models.CASCADE)

class CarritoDeCompras(models.Model):
	idCarrito 	= models.AutoField(primary_key=True)
	idProducto 	= models.ForeignKey(Producto,null=False,blank=False,on_delete=models.CASCADE)
	idCliente 	= models.ForeignKey(Cliente,null=False,blank=False,on_delete=models.CASCADE)
	cantidad  	=models.IntegerField(default=0)
	descuento 	=models.FloatField(default=0)

apps/pagos/models.py
from django.db import models

# Create your models here.

apps/cliente/forms.py
from django import forms

from apps.registro.models import Persona
from apps.cliente.models import Pedidos


class CrearPedidoForm(forms.ModelForm):
	class Meta:
		model = Pedidos
		fields = [
				#'idCliente',
				'nombre',
				'categoria',
				'descripcion',
				#'fecha_pedido',
		]
		labels = {
				'nombe': '¿ Qué esta buscando ?',
				'categoria':'Eliga una categoría',
				'descripcion': 'De una descripción',
		}
		categoriasList = (
			('computo', 'Computo'),
			('moda', 'Moda'),
			('celulares', 'Celulares'),
			('hogar', 'Hogar'),
			('deportes', 'Deportes'),
			('jugueteria', 'Jugueteria'),
		)
		
		widgets ={
				'nombre':forms.TextInput(attrs={'class':'form-control'}),
				'categoria':forms.Select(attrs={'class': 'form-control'}, choices=( (x ) for x in categoriasList ),),
				'descripcion':forms.TextInput(attrs={'class': 'form-control'}),
		}

apps/carrito/views.py
from django.shortcuts import render

# Create your views here.

apps/cliente/views.py
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.shortcuts import redirect
from apps.tienda.views import error404
from django.template import RequestContext
from django.http import HttpResponseRedirect
from django.views.generic import ListView

from django.http import HttpResponse
from apps.registro.models import Persona
from apps.registro.forms import RegistroForm, RegistroUsuarioForm
from apps.cliente.models import Cliente, Pedidos
from apps.cliente.forms import CrearPedidoForm
from django.contrib import auth
from apps.cliente.models import CarritoDeCompras, Lista_deseos


from datetime import datetime
from apps.proveedor.models import Producto
from apps.proveedor.models import Categoria

# Create your views here.

def index(request):
	if 'isLogin' not in request.session or request.session.get('permisos')!='cliente':
		return redirect('/')
	
	keywords=''
	categoria=''
	if 'categoria' in request.GET and  request.GET['categoria'] != "" :	
		categoria= request.GET['categoria']
		ofertas = Producto.objects.filter(categoria__icontains = categoria ) ## CAMBIAR DE PRODUCTOS A OFERTAS Y PROMOCIONES
	
	else:
		if 'query' in request.GET and  request.GET['query'] != "" :	
			keywords= request.GET['query']
			ofertas = Producto.objects.filter(nombre__icontains = keywords ) ## CAMBIAR DE PRODUCTOS A OFERTAS Y PROMOCIONES
		else:
			ofertas = Producto.objects.select_related() ## CAMBIAR DE PRODUCTOS A OFERTAS Y PROMOCIONES
	
	categorias=Categoria.objects.all()

	#obtenemos el id de la persona usando el id cliente
	#IDpersona = Persona.objects.get(idUsuario_id =request.session['id_user'])
	idUsuario = request.session.get('id_user')
	usuario = request.session.get('usuario')
	clienteComoPersona = Persona.objects.get(idUsuario_id=idUsuario)
	IDcliente = Cliente.objects.get(persona_id =clienteComoPersona.idPersona)
	
	#obtenemos la fecha actual 
	if request.method == 'POST':
		form_pedido = CrearPedidoForm(request.POST or None)
		if form_pedido.is_valid():
			#obtenemos lod datos llenados desde el formulario
			datos_pedido = form_pedido.save(commit=False)
			#E llenamos los campos que no se llenaron desde formulario
			datos_pedido.fecha_pedido = datetime.now()
			#Guardamos el id del cliente actual en el pedido realizado
			datos_pedido.idCliente_id=IDcliente.idCliente
			datos_pedido.save()
	else: 
		form_pedido = CrearPedidoForm()
	contexto= {'mis_categorias': categorias, 'ofert_list' : ofertas,'form_pedido':form_pedido,'keywords':keywords,'categoria': categoria}
	return render(request, 'cliente/index.html', contexto)


def perfilCliente(request):
    ## VALIDACION PARA SABER SI EL USUARIO HA SIDO LOGEADO Y SI TIENE PERMISOS PARA ACCEDER
	if request.session.get('isLogin') != True or request.session.get('permisos') != 'cliente':
		return error404(request);
	idUsuario = request.session.get('id_user')
	usuario = Persona.objects.filter(idUsuario_id=idUsuario)
	contexto= {'mi_usuario':usuario , 'id_user':idUsuario}
	return render(request,'cliente/perfil.html',contexto)   



#muestra la interfaz de los pedidos del cliente
def mostrarPedidos(request):
	#obtenemos el id de la persona usando el id cliente
	#IDpersona = Persona.objects.get(idUsuario_id =request.session['id_user'])
	idUsuario = request.session.get('id_user')
	usuario = request.session.get('usuario')
	clienteComoPersona = Persona.objects.get(idUsuario_id=idUsuario)
	IDcliente = Cliente.objects.get(persona_id =clienteComoPersona.idPersona)
	lista_pedidos = Pedidos.objects.filter(idCliente_id=IDcliente.idCliente)
	contexto= {'lista_pedidos':lista_pedidos,'mi_usuario':usuario , 'id_user':idUsuario}
	return render(request, 'cliente/pedidos.html', contexto)

def crearPedido(request):
	print("=====================Pedido procesando========================")
	#obtenemos el id de la persona usando el id cliente
	#IDpersona = Persona.objects.get(idUsuario_id =request.session['id_user'])
	idUsuario = request.session.get('id_user')
	usuario = request.session.get('usuario')
	clienteComoPersona = Persona.objects.get(idUsuario_id=idUsuario)
	IDcliente = Cliente.objects.get(persona_id =clienteComoPersona.idPersona)
	print(IDcliente.idCliente)
	#obtenemos la fecha actual 
	if request.method == 'POST':
		print("metodo post")
		form_pedido = CrearPedidoForm(request.POST or None)

		if form_pedido.is_valid():
			print("validado")
			#obtenemos lod datos llenados desde el formulario
			datos_pedido = form_pedido.save(commit=False)
			#llenamos los campos que no se llenaron desde formulario
			datos_pedido.fecha_pedido = datetime.now()
			#Guardamos el id del cliente actual en el pedido realizado
			datos_pedido.idCliente_id=IDcliente.idCliente
			datos_pedido.save()
			return redirect('/cliente/pedidos')
	else: 
		print("no validado")
		form_pedido =CrearPedidoForm()
		
	contexto= {'form_pedido':form_pedido,'mi_usuario':usuario , 'id_user':idUsuario}
	return render(request, 'cliente/crearPedido.html', contexto)

#editaremos un pedido
def editarPedido(request,idp):
	pedido = Pedidos.objects.get(idPedido = idp)
	print(pedido.nombre)
	if request.method =="POST":
		form_pedido = CrearPedidoForm(request.POST or None)
		if form_pedido.is_valid():
			pedido.nombre = form_pedido.cleaned_data['nombre']
			pedido.categoria = form_pedido.cleaned_data['categoria']
			pedido.descripcion = form_pedido.cleaned_data['descripcion']
			pedido.save()
			return redirect('/cliente/pedidos') 
	if request.method == "GET":
		form_pedido = CrearPedidoForm(initial={
			'nombre': pedido.nombre,
			'categoria': pedido.categoria,
			'descripcion': pedido.descripcion,
			})
	contexto = {'form_pedido':form_pedido, 'pedido':pedido}
	return render(request,'cliente/crearPedido.html',contexto)
	
#eliminamos pedidosDescripción de laptop Lenovo
def eliminarPedido(request, idp):
	cliente = Pedidos.objects.get(idPedido=idp)
	Pedidos.objects.filter(idPedido = idp).delete()
	lista_pedidos = Pedidos.objects.filter(idCliente=cliente.idCliente_id)
	return  redirect('/cliente/pedidos')



def carritoCliente(request):    
	idUsuario = request.session.get('id_user')
	clienteComoPersona = Persona.objects.get(idUsuario_id=idUsuario)
	IDcliente = Cliente.objects.get(persona_id =clienteComoPersona.idPersona)
	listaCarrito = CarritoDeCompras.objects.filter(idCliente = IDcliente.idCliente).select_related()
	categorias=Categoria.objects.all()
	

	if 'id' not in request.GET or 'cant' not in request.GET or request.session.get('permisos') != 'cliente': 
		item_set={	'listaCarrito':listaCarrito}
		return render(request, 'cliente/carrito.html',item_set)

	idProducto= request.GET['id']
	cantProducto=request.GET['cant']
	item =Producto.objects.filter(idProducto=idProducto).all()
	
	if len(item) != 1:
		return render(request, 'cliente/carrito.html')
	
	statusCarrito=False	

	if 'isLogin' in request.session and request.session.get('permisos') =='cliente':
		idUsuario = request.session.get('id_user')
		idPersona =  Persona.objects.filter(idUsuario=idUsuario).all()[0].idPersona
		cliente= Cliente.objects.filter(persona=idPersona).all()[0]
		estado = CarritoDeCompras.objects.filter(idCliente=cliente.idCliente, idProducto=item[0])
		
		if not estado:
			itemCarrito = CarritoDeCompras(cantidad=cantProducto,descuento=0,idCliente=cliente, idProducto=item[0])
			itemCarrito.save()	
			statusCarrito=True				
	else:
		return redirect('/registro')
	
	item_set={'mis_categorias':categorias,'detalles' : item,'id':idProducto,'estadoCarrito':statusCarrito,'listaCarrito':listaCarrito}
	return render(request, 'cliente/carrito.html',item_set)

#Editamos informacion del usuario
def editarInformacion_view(request, id_user):
	usuario = Persona.objects.get(idPersona = id_user)
	print(usuario.nombres)
	if request.method =="POST":
		form = RegistroForm(request.POST or None)
		if form.is_valid():
			usuario.nombres = form.cleaned_data['nombres']
			usuario.apellidos = form.cleaned_data['apellidos']
			usuario.sexo = form.cleaned_data['sexo']
			usuario.fecha_nac = form.cleaned_data['fecha_nac']
			usuario.id_doc = form.cleaned_data['id_doc']
			usuario.telf = form.cleaned_data['telf']
			usuario.domicilio = form.cleaned_data['domicilio']
			usuario.save()
			return redirect('/cliente/perfil')
		#return render(request,'cliente/perfil.html',{'mi_usuario':usuario})   
	if request.method == "GET":
		form_editar = RegistroForm(initial={
			'nombres': usuario.nombres,
			'apellidos': usuario.apellidos,
			'sexo':usuario.sexo,
			'fecha_nac': usuario.fecha_nac,
			'id_doc': usuario.id_doc,
			'telf':usuario.id_doc,
			'domicilio':usuario.domicilio,
			})
		contexto = {'form_editar':form_editar, 'usuario':usuario}
		return render(request,'cliente/editarInf.html',contexto)

def listaDeseos(request):
	idUsuario = request.session.get('id_user') 
	clienteComoPersona = Persona.objects.get(idUsuario_id=idUsuario) 
	IDcliente = Cliente.objects.get(persona_id =clienteComoPersona.idPersona) 
	favoritos = Lista_deseos.objects.filter(idCliente = IDcliente.idCliente).select_related() 
	contexto = {'favoritos':favoritos} 
	return render(request,'cliente/lista_deseos.html',contexto) 
 
def eliminarFavorito(request, idf): 
	Lista_deseos.objects.filter(id = idf).delete() 
	return  redirect('/cliente/deseos') 
	#return render(request,'cliente/lista_deseos.html',contexto) 


def pagos(request):
    	return render(request,'cliente/pagos.html')

apps/pagos/views.py
from django.shortcuts import render

# Create your views here.

templates/cliente/carrito.html
    {% extends 'base/base.html' %}

{% load staticfiles %}
{% block title %}
iSeller - Perfil
{% endblock %}


{% block content %}




<div id="heading-breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <h1>Carrito de Compras </h1>
            </div>
            <div class="col-md-6">
                <ul class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li>Shopping cart</li>
                </ul>

            </div>
        </div>
    </div>
</div>

<div id="content">
    <div class="container">

        <div class="row">
            {% block estadoCarrito %}
                {%if estadoCarrito %}
                    <div class="alert alert-success alert-dismissable fade in">
                        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                            <strong>Agregado!</strong> {{ detalles.0.nombre }} fue agregado a su Carrito de Compras.
                    </div>
                {%endif%}
                
            {% endblock %}
            <div class="col-md-12">
                <p class="text-muted lead">Productos en tu carrito de compras : </p>
            </div>


            <div class="col-md-9 clearfix" id="basket">

                <div class="box">

                    <form method="post" action="shop-checkout1.html">

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th colspan="2">Producto</th>
                                        <th>Cantidad</th>
                                        <th>Precio por unidad</th>
                                        <th>Descuento</th>
                                        <th colspan="2">Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                <!-- ITEM  -->
                                
                                {% for item in listaCarrito%}
                                    <tr>
                                        <td>
                                            <a href="#">
                                                <img src="/media/{{ item.idProducto.urlImagen }}" alt="White Blouse Armani">
                                            </a>
                                        </td>
                                        <td><a href="#">{{ item.idProducto.nombre }}</a>
                                        </td>
                                        <td>
                                            <input type="number" value="{{ item.cantidad }}" class="form-control">
                                        </td>
                                        <td>S/. {{item.idProducto.precioBasico}}</td>
                                        <td>{{ item.descuento }}</td>
                                        <td>{{ item.idProducto.precioBasico }}</td>
                                        <td><a href="#"><i class="fa fa-trash-o"></i></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                                <!-- /ITEM  -->
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <th colspan="5">Total</th>
                                        <th colspan="2">$446.00</th>
                                    </tr>
                                </tfoot>
                            </table>

                        </div>
                        <!-- /.table-responsive -->

                        {%if listaCarrito%}
 

                            <div class="box-footer">
                                <div class="pull-left">
                                    <a href="\" class="btn btn-default"><i class="fa fa-chevron-left"></i> Continue shopping</a>
                                </div>
                                <div class="pull-right">
                                    <a id="miBoton" class="btn btn-template-main" href="#" onclick="Pagar({{listaCarrito|safe}});" >Realizar el pago</a>
                                </div>               
                            </div>  
                        {%endif%}
 
         
                        
                    </form>
                    <div class="panel panel-default" id="response-panel">
                        <div class="panel-body" id="response">La operación se realizó </div>
                    </div>

              
                    

                </div>
                <!-- /.box -->
             <!--   
                <div class="row">
                    <div class="col-md-3">
                        <div class="box text-uppercase">
                            <h3>Recomendaciones</h3>
                        </div>
                    </div>

                    <div class="col-md-3">
                        <div class="product">
                            <div class="image">
                                <a href="shop-detail.html">
                                    <img src="{% static 'img/product2.jpg' %}" alt="" class="img-responsive image1">
                                </a>
                            </div>
                            <div class="text">
                                <h3><a href="shop-detail.html">Fur coat</a></h3>
                                <p class="price">$143</p>

                            </div>
                        </div>                
                    </div>
                </div>
            -->



      
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
            <script src="https://checkout.culqi.com/plugins/v2"></script>
            <script type="text/javascript" src="{% static 'js/waitMe.min.js' %}"></script>
            <script>
            $("#response-panel").hide();
            Culqi.publicKey = 'pk_test_vzMuTHoueOMlgUPj';
            Culqi.settings({
                title: 'Culqi Store',
                currency: 'PEN',
                description: 'Polo/remera Culqi lover',
                amount: 3500
            });
            $('#miBoton').on('click', function (e) {
                // Abre el formulario con las opciones de Culqi.configurar
                Culqi.open();
                e.preventDefault();
            });
            // Recibimos Token del Culqi.js
            function culqi() {
              if (Culqi.token) {
                  $(document).ajaxStart(function(){
                    run_waitMe();
                  });
                  // Imprimir Token
                  $.ajax({
                     type: 'POST',
                     url: '/culqi/charges',
                     data: { csrfmiddlewaretoken: '{{ csrf_token }}', token: Culqi.token.id, installments: Culqi.token.metadata.installments },
                     datatype: 'json',
                     success: function(data){
                       var result = "";
                       if(data.constructor == String){
                           result = JSON.parse(data);
                       }
                       if(data.constructor == Object){
                           result = JSON.parse(JSON.stringify(data));
                       }
                       if(result.object === 'charge'){
                         resultdiv(result.outcome.user_message);
                       }
                       if(result.object === 'error'){
                           resultdiv(result.user_message);
                       }
                     },
                     error: function(error) {
                       resultdiv(error);
                     }
                  });
              } else {
                // Hubo un problema...
                // Mostramos JSON de objeto error en consola
                resultdiv(Culqi.error.user_message);
              }
            };
            function run_waitMe(){
              $('body').waitMe({
                effect: 'orbit',
                text: 'Procesando pago...',
                bg: 'rgba(255,255,255,0.7)',
                color:'#28d2c8'
              });
            }
            function resultdiv(message){
              $('#response-panel').show();
              $('#response').html(message);
              $('body').waitMe('hide');
            }
            </script>



            </div>

        </div>

    </div>
    <!-- /.container -->
</div>
<!-- /#content -->


{% endblock%}


templates/cliente/crearPedido.html
{% extends 'cliente/pedidos.html' %}
{% load staticfiles %}

{% block title %}
Perfil Cliente : {{  mi_usuario.0.nombres }} 
{% endblock %}
{% block contentPedidos%}
		<h3 class="text-uppercase">Crear Pedido</h3>
			</div>
		</div>	
		<div class="col-md-12"  style="border-top:1px; margin-top:5px">
			<div style="padding: 10px;" class="row">
				 <form  method="POST" action=" ">
						{% csrf_token %}
                        {{ form_pedido.as_p}}
                        <div class="text-right">
                        <button type="submit"  class="btn btn-template-main"><i class="fa fa-user-md"></i> Guardar</button>                                 
                        </div>
                        </form>
			</div>
		</div>

{% endblock%}

templates/cliente/editarInf.html
{% extends 'cliente/perfil.html' %}

{%block informacion%}
<div class="heading col-md-10">
	<h3 class="text-uppercase">Mi Perfil</h3>
</div>
<div class="col-md-9" >
	<form method="POST" accept=".">
	 	{% csrf_token %}
	 	{{ form_editar.as_p}}   
	 	 <div class="text-center">
          <button type="submit" class="btn btn-template-main">Guardar Datos</button>
          </div>                                         
	</form>                                        
</div>
{%endblock%}

templates/cliente/index.html
	{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}
iSeller - Una Nueva Forma de comprar
{% endblock %}

{% block content%}

	<div id="heading-breadcrumbs">
		<div class="container">
			<div class="row">
				<div class="col-md-7">
					<h2>Una nueva manera de comprar</h>
					<!-- Prueba -->
  				</div>
				<div class="col-md-5">
					<ul class="breadcrumb">
						<li>Inicio/</a>						
					</ul>
				</div>
			</div>
		</div>
	</div>
	

	<div id="content">
		<div class="container">
			<div class="row">
				<!-- *** LEFT COLUMN ***
		_________________________________________________________ -->

				<div class="col-sm-3">

					<!-- *** MENUS AND FILTERS ***
_________________________________________________________ -->
					<div class="panel panel-default sidebar-menu">

						<div class="panel-heading">
							<h3 class="panel-title">Categorias</h3>
						</div>

						<div class="panel-body">
							<ul class="nav nav-pills nav-stacked category-menu">
								{%if mis_categorias%}
								{%for categoria in mis_categorias %}
								<li>
									<a href="/?categoria={{categoria.nombre}}">{{categoria.nombre}}<span class="badge pull-right"></span></a>
								</li>
								{%endfor%}
								{%endif%}
							</ul>
						</div>
					</div>


					<div class="banner">
						<a href="shop-category.html">
							<img src="{% static 'img/banner.jpg' %}" alt="sales 2014" class="img-responsive">
						</a>
					</div>

					<!-- /.banner -->

				</div>
				<!-- /.col-md-3 -->

				<!-- *** LEFT COLUMN END *** -->

				<!-- *** RIGHT COLUMN ***-->

				
				<div class="col-sm-9">
					
					<div class="row">
						<div class="input-group">									
							<span class="input-group-btn">
								<form action="\" method="GET">
										{% csrf_token %}
									<div class="col-md-10" >
										<input class="form-control" name="query" placeholder="Buscar un producto" type="text">
										<button  type="submit" class="btn btn-template-main"><i class="fa fa-search"></i>Buscar</button>										
									</div>
								</form>
								
							</span>				
						</div>
						
						<br>
						
							<div class="text-center">

								<a class="btn btn-template-primary btn-lg" href="#formPedido" class="btn btn-template-main" data-toggle="modal">
									<i class="fa fa-bullhorn"></i>
									Crear un Pedido
								</a>
							</div>
								<!--clase modal para crear pedidos-->
								<div class="modal fade" id="formPedido">
									<div class="modal-dialog">
										<div class="modal-content">
											<div class="modal-header">
												<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
												<h2 class="modal-title"> Crear Pedido</h2>
												<p><strong>¿ Quieres una atención más personalizada ?</strong> Envianos tu pedido, y te responderemos lo más pronto posible. Disfruta de una una forma de comprar más personalizada</p>
											</div>
												{% block javascript %}
											  <script>
											      function pruebax()
											      {
											      		var aux="Ha solicitado "+ $("#id_nombre").val();
											      		console.log(aux);
											      		$.ajax({
														        url: 'test_noti',
														        data: {
														          'mensaje': aux
														        },
														        dataType: 'json',
														        success: function (data) {
														          if (data.is_taken) {
														            alert("A user with this username already exists.");
														          }
														        }
														      });
											    	}
											  </script>
											{% endblock %}
											<div class="modal-body">
												 <form  method="POST" action=" ">
													{% csrf_token %}
													{{ form_pedido.as_p}}          
												<div class="text-center" onClick="pruebax();">
													
													<button type="submit" class="btn btn-template-main" ><i class="fa fa-send"></i> Enviar pedido </button>
												</div>
											</form>
		
											</div>
										</div>
									</div>
								</div>
					</div>
								

							
					<div class="banner">
						<a href="shop-category.html">
							<img src="{% static 'img/banner4.jpg' %}" alt="sales 2014" class="img-responsive">
						</a>
					</div>
					<hr>


					<div class="row products">

							{% if ofert_list %}
							
							{% for  item in ofert_list %}

							<div class="col-md-4 col-sm-6">
									<div class="product" style="    
									width: 100%; 
									height: 320px; 
									overflow: hidden; ">
										<div class="image">
											<a href="/detalles?id={{ item.idProducto }}">
												<img src="/media/{{ item.urlImagen }}" alt="" class="img-responsive image1">
											</a>
										</div>
										<!-- /.image -->
										<div class="text">
											<h4><a href="/detalles?id={{ item.idProducto }}">{{ item.nombre }} </a></h4>
											<h4> {{ item.marca }}</h4>
											<p class="price"><del>indefinido</del> ${{item.precioBasico}}</p>
											<p class="buttons">
												<a href="shop-detail.html" class="btn btn-default">View detail</a>
												<a href="shop-basket.html" class="btn btn-template-main"><i class="fa fa-shopping-cart"></i>Add to cart</a>
											</p>
										</div>
										<!-- /.text -->
		
										<div class="ribbon sale">
											<div class="theribbon">SALE</div>
											<div class="ribbon-background"></div>
										</div>
										<!-- /.ribbon -->
		
										<div class="ribbon new">
											<div class="theribbon">NEW</div>
											<div class="ribbon-background"></div>
										</div>
										<!-- /.ribbon -->
									</div>
									<!-- /.product -->
								</div>
							{% endfor %} 
							{% else %}
							Error, no se encontraron productos
							{% endif %}
					
						<!-- /.col-md-4 -->
					</div>
					<!-- /.products -->

					<div class="row">

						<div class="col-md-12 banner">
							<a href="#">
								<img src="{% static 'img/banner3.jpg' %}" alt="" class="img-responsive">
							</a>
						</div>

					</div>


					<div class="pages">

						<p class="loadMore">
							<a href="#" class="btn btn-template-main"><i class="fa fa-chevron-down"></i> Load more</a>
						</p>

						<ul class="pagination">
							<li><a href="#">&laquo;</a>
							</li>
							<li class="active"><a href="#">1</a>
							</li>
							<li><a href="#">2</a>
							</li>
							<li><a href="#">3</a>
							</li>
							<li><a href="#">4</a>
							</li>
							<li><a href="#">5</a>
							</li>
							<li><a href="#">&raquo;</a>
							</li>
						</ul>
					</div>


				</div>
				<!-- /.col-md-9 -->

				<!-- *** RIGHT COLUMN END *** -->

			</div>

		</div>
		<!-- /.container -->
	</div>
	<!-- /#content -->


{%endblock%}